-- =========================================
-- SEQUENCES
-- =========================================
CREATE SEQUENCE SEQ_COMPANY
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE SEQ_ENVIRONMENTAL_LICENSE
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE SEQ_CARBON_EMISSION
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE SEQ_ENVIRONMENTAL_AUDIT
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE SEQ_ENVIRONMENTAL_ALERT
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- =========================================
-- ENTITIES
-- =========================================
CREATE TABLE TB_COMPANY (
    ID INTEGER DEFAULT SEQ_COMPANY.NEXTVAL PRIMARY KEY,
    NAME VARCHAR2(150) NOT NULL,
    CNPJ VARCHAR2(18) NOT NULL UNIQUE,
    CREATED_AT DATE DEFAULT SYSDATE
);

CREATE TABLE TB_ENVIRONMENTAL_LICENSE (
    ID INTEGER DEFAULT SEQ_ENVIRONMENTAL_LICENSE.NEXTVAL PRIMARY KEY,
    COMPANY_ID NUMBER NOT NULL,
    TYPE VARCHAR2(100) NOT NULL,
    ISSUE_DATE DATE NOT NULL,
    EXPIRATION_DATE DATE NOT NULL,
    STATUS VARCHAR2(50),
    CONSTRAINT FK_LICENSE_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES TB_COMPANY(ID)
);

CREATE TABLE TB_CARBON_EMISSION (
    ID INTEGER DEFAULT SEQ_CARBON_EMISSION.NEXTVAL PRIMARY KEY,
    COMPANY_ID NUMBER NOT NULL,
    AMOUNT NUMBER(10,2) NOT NULL,
    LIMIT_VALUE NUMBER(10,2) NOT NULL,
    STATUS VARCHAR2(50),
    CREATED_AT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_EMISSION_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES TB_COMPANY(ID)
);

CREATE TABLE TB_ENVIRONMENTAL_AUDIT (
    ID INTEGER DEFAULT SEQ_ENVIRONMENTAL_AUDIT.NEXTVAL PRIMARY KEY,
    COMPANY_ID NUMBER NOT NULL,
    RESULT VARCHAR2(20) NOT NULL,
    NOTES VARCHAR2(500),
    AUDIT_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_ENV_AUDIT_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES TB_COMPANY(ID)
);

CREATE TABLE TB_ENVIRONMENTAL_ALERT (
    ID INTEGER DEFAULT SEQ_ENVIRONMENTAL_ALERT.NEXTVAL PRIMARY KEY,
    TYPE VARCHAR2(50) NOT NULL,
    DESCRIPTION VARCHAR2(255),
    CREATED_AT DATE DEFAULT SYSDATE,
    REFERENCE_ID NUMBER,
    REFERENCE_TYPE VARCHAR2(50)
);