CREATE SEQUENCE SEQ_USER
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE TB_USER (
    ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(255) NOT NULL
);